.\" Man page for e2-create-project
.\"
.\" (c)2007 emlix GmbH
.\"
.TH e2-create-project 1 "Aug 6, 2007" "0.1"

.SH NAME
e2-create-project \- create a new project

.SH SYNOPSIS
e2-create-project [<option> ...] [<server>:]<location>

.SH DESCRIPTION
Create a new project and store it on <server> in <location>.
<server> defaults to 'projects'.
The project name will be the basename of <location>.
The usual project location convention is
\fBprojects:<customer>/<projectname>\fR. 

.SH RETURN VALUE
Normally, exit status is 0. On error, it is non-zero.

.SH OPTIONS
.TP
.BR \-\-help
Show usage information.
.TP
.BR \-\-version
Show version number of e2.

.P
For further global options, see \fBe2intro\fR(7).

.SH BUGS
Doubtless there are many.

.SH "SEE ALSO"
.BR e2intro(7)
.BR e2global(7)
.BR e2-fetch-project(1)
.BR e2-fetch-sources(1)
.BR e2-ls-project(1)
.BR e2config(5)

.SH AUTHORS
Gordon Hecker, Oskar Schirmer and Felix Winkelmann

.SH COPYRIGHT
(c)2007 emlix GmbH
