.\" Man page for <tool>
.\"
.\" (c)2007 emlix GmbH
.\"
.TH <tool> 1 "Dec 12, 2007" "2.1"

.SH NAME
e2-cf \- modify and create configuration files

.SH SYNOPSIS
usage: e2 cf <command> ...

.SH DESCRIPTION
commands are:
 newresult       <name>
 newsource       <name> <scm>
 editresult      <name>
 editbuildscript <name>
 editsource      <name>

Commands starting with 'edit' can be abbreviated by using e...
Commands starting with 'new' can be abbreviated by using n...
Commands can be shortened as long as they remain unambiguous

e.g.: eb <name> is equivalent to editbuildscript <name>

Templates are used as initial config files. An editor is started
for each file that must be configured by the user.

.SH RETURN VALUE
Normally, exit status is 0. On error, it is non-zero.

.SH OPTIONS
.TP
.BR \-\-help
Show usage information.
.P
For further global options, see \fBe2intro\fR(7).

.SH EXAMPLES
The following three commands do exactly the same: Create a new result
configuration for a result named 'foo':
.IP
.nf
e2-cf newresult foo
e2-cf newr foo
e2-cf nr foo
.PP

.SH ENVIRONMENT
e2-cf uses the EDITOR environment variable to determine which editor to
start. The default editor is 'vi'.

.SH BUGS
Doubtless there are many.

.SH "SEE ALSO"
.BR e2intro (7).

.SH AUTHORS
Gordon Hecker, Oskar Schirmer and Felix Winkelmann

.SH COPYRIGHT
(c)2007 emlix GmbH
