.\" Man page for e2-dlist
.\"
.\" (c)2007 emlix GmbH
.\"
.TH e2-dlist 1 "Aug 3, 2007" "0.1"

.SH NAME
e2-dlist \- list dependencies of a particular result

.SH SYNOPSIS
e2-dlist [OPTION|RESULT ...]

.SH DESCRIPTION
\fBe2-dlist\fR shows the direct dependencies of a result, i.e. the
results that are required to be built before the argument result can
be created. In other words, the listed results are
\fBbuild-time dependencies\fR of the argument result.

.SH RETURN VALUE
Normally, exit status is 0. On error, it is non-zero.

.SH OPTIONS
.TP
.BR \-\-recursive
Show indirect dependencies as well. Normally only direct dependencies
are shown.
.TP
.BR \-\-help
Show usage information.

.P
For further global options, see \fBe2intro\fR(7).

.SH BUGS
Doubtless there are many.

.SH "SEE ALSO"
.BR e2intro (7),
.BR e2-dsort (1),
.BR e2-ls-project (1),
.BR e2config (5).

.SH AUTHORS
Gordon Hecker, Oskar Schirmer and Felix Winkelmann

.SH COPYRIGHT
(c)2007 emlix GmbH
