.\" Man page for e2-fetch-sources
.\"
.\" (c)2007 emlix GmbH
.\"
.TH e2-fetch-sources 1 "Aug 3, 2007" "0.1"

.SH NAME
e2-fetch-sources \- retrieve sources for the current project

.SH SYNOPSIS
e2-fetch-sources [OPTION|SOURCE|RESULT ...]

.SH DESCRIPTION
\fBe2-fetch-sources\fR retrieves sources for project results. Sources can be
either specified through the source- or result names. For sources stored
in version-controlled repositories, the associated repositories will be 
cloned and a project-local working copy created. Invokes the
"fetch-sources" hook.

Note, that sources of type \fIfiles\fR are not fetched.

Note, that sources are not fetched again, where fetched yet.
Moreover, the local working copy at \fIin/SOURCE\fR is not checked for
up-to-dateness.
Thus, to refetch sources, remove the outdated working copy,
then fetch again.

.SH RETURN VALUE
Normally, exit status is 0. On error, it is non-zero.

.SH OPTIONS
.TP
.BR \-\-all
Fetch all sources refered to in the whole project.
.TP
.BR \-\-source
Fetch sources by source name.
.TP
.BR \-\-result
Fetch sources by result name.
.TP
.BR \-\-help
Show usage information.
.P
For further global options, see \fBe2intro\fR(7).

.SH BUGS
Doubtless there are many.

.SH "SEE ALSO"
.BR e2intro (7),
.BR e2-ls-project (1),
.BR e2config (5),
.BR e2hooks (7).

.SH AUTHORS
Gordon Hecker, Oskar Schirmer and Felix Winkelmann

.SH COPYRIGHT
(c)2007 emlix GmbH
