.\" Man page for e2-playground
.\"
.\" (c)2007 emlix GmbH
.\"
.TH e2-playground 1 "Aug 9, 2007" "0.1"

.SH NAME
e2-playground \- enter chroot(1) environment for specified result


.SH SYNOPSIS
e2-playground OPTION|RESULT ...

.SH DESCRIPTION
\fBe2-playground\fR enters a \fBchroot\fR(1) environment previously
created by running \fBe2-build\fR with the "--playground" option, or
one that is left over from a previous (possibly failed) build.

.SH RETURN VALUE
Normally, exit status is 0. On error, it is non-zero.

.SH OPTIONS
.TP
.BR \-\-command\=CMD
Execute \fBCMD\fR in the chroot(1) environment, instead of running
an interactive shell.
.TP
.BR \-\-showpath
Print path to chroot(1) environment.
.TP
.BR \-\-help
Show usage information.
.P
For further global options, see \fBe2intro\fR(7).

.SH BUGS
Doubtless there are many.

.SH "SEE ALSO"
.BR e2intro (7),
.BR e2-ls-project (1),
.BR e2-build (1),
.BR e2config (5),

.SH AUTHORS
Gordon Hecker, Oskar Schirmer and Felix Winkelmann

.SH COPYRIGHT
(c)2007 emlix GmbH
