.\" Man page e2-global
.\"
.\" (c)2007 emlix GmbH
.\"
.TH e2-global 7 "Sep 11, 2007" "0.2"

.SH NAME
e2global \- e2 global tools

.SH DESCRIPTION
There is a set of global tools with a well-defined interface to
projects stored on a server and projects checked out as a working
copy.
This interface is versioned using files named \fBversion\fR in the
project directory on the server, and \fB.e2/version\fR in the project
repository.
These files store integer version ids. They state which version of 
global code may be used to perform certain tasks on a project.

.nf
The interfaces cover: 
 * how to create a project
 * how to checkout a project from the server
 * how to install the local e2 tools into a project
 * how to call local tools
.fi

.SH BUGS
Doubtless there are many.

.SH "SEE ALSO"
.BR e2-fetch-sources(1)
.BR e2-create-project(1)
.BR e2(1)
.BR e2intro(7)

.SH AUTHORS
Gordon Hecker, Oskar Schirmer and Felix Winkelmann

.SH COPYRIGHT
(c)2007 emlix GmbH
