.\" Man page for e2rc
.\"
.\" (c)2007 emlix GmbH
.\"
.TH e2rc.5 "Aug 2, 2007" "0.1"

.SH NAME
e2rc \- per-user default settings for local e2 tools

.SH SYNOPSIS
e2rc [OPTION/PATH]...

.SH DESCRIPTION
\fB$HOME/.e2/e2rc\fR has the following format:

 e2rc {
   { "option" [, value] },
   ...
 }

where \fBoption\fR must be the name of a valid command line option and value
can be \fBtrue\fR or \fBfalse\fR for flags or a quoted string for options
that take an argument.
Omitting the value is equivalent to specifying \fBtrue\fR.
Options given on the command line override options specified in
\fBe2rc\fR.

Example:

 e2rc {
   { "debug" }
 }

.SH BUGS
Doubtless there are many.

.SH "SEE ALSO"
.BR e2intro (7).

.SH AUTHORS
Gordon Hecker, Oskar Schirmer and Felix Winkelmann

.SH COPYRIGHT
(c)2007 emlix GmbH
