.\" Man page for <tool>
.\"
.\" (c)2007 emlix GmbH
.\"
.TH <tool> 1 "Dec 12, 2007" "2.1"

.SH NAME
<tool> \- <description>

.SH SYNOPSIS
<tool> [OPTION/PATH]...

.SH DESCRIPTION
\fB<tool>\fR blablabla.

.SH RETURN VALUE
Normally, exit status is 0. On error, it is non-zero.

.SH OPTIONS
.TP
.BR \-\-help
Show usage information.
.P
For further global options, see \fBe2intro\fR(7).

.SH BUGS
Doubtless there are many.

.SH "SEE ALSO"
.BR e2intro (7).

.SH AUTHORS
Gordon Hecker, Oskar Schirmer and Felix Winkelmann

.SH COPYRIGHT
(c)2007 emlix GmbH
