#!/bin/sh
export LC_ALL=C
while [ '!' -f .e2/e2version ] ; do
	if [ "$PWD" = "/" ] ; then
		echo >&2 \
		    "e2-locate-project-root: Not in a project environment."
		exit 1
	fi
	cd ..
done
echo $PWD
